#' Nomogram outputs using the estimated value of numerical outcome
#'
#' An example of a data frame for `sample_output` argument in 
#' \code{\link{create_nomogram}} function, must only include the estimated 
#' values for numerical outcome.
#'
#' @format A data frame with 16 rows and 1 column:
#' \describe{
#'   \item{output}{A numerical outcome.}
#' }
#'
#' @source Generated by a caret randomforest model using categorical predictors 
#' for examples in this package.
#' @keywords dataset
#' @name nomogram_outputs3
'nomogram_outputs3'
