#' Nomogram outputs using the predicted probability of binary outcome
#'
#' An example of a data frame for `sample_output` argument in 
#' \code{\link{create_nomogram}} function, must only include the predicted 
#' probabilities for binary outcome.
#'
#' @format A data frame with 16 rows and 1 column:
#' \describe{
#'   \item{output}{A binary outcome with values from 0 to 1.}
#' }
#'
#' @source Generated by a caret randomforest model using categorical predictors 
#' for examples in this package.
#' @keywords dataset
#' @name nomogram_outputs
'nomogram_outputs'
